# CORS allowed origin for the frontend
allowed_origin = "http://fluxgate.example.com"

# Address that the Actix-Web HTTP server binds to
http_addr = "0.0.0.0:8080"

# Address that the gRPC server binds to
grpc_addr = "0.0.0.0:50051"
